### ISSUE TITLE
offset值无法更新

### ISSUE THREAD

**Issue by lention** [franknew/RocketMQ-Client#2]
frank，你好，我最近做一些尝试，使用了你提供的rocketmq-client(c#) 组件，但是我在采用pull方式消费消息后通过调用 consumer.updateConsumeOffset(queue, pullResult.getNextBeginOffset());进行offset的更新，但这个值并没有被更新到broker上。所以导致同一个数据一直被不停的消费。

需要说明的是我的消费模式是：consumer.setMessageModel(MessageModel.CLUSTERING);

不知你是否清楚原因，或者是否有示例代码以供参考。

如有任何建议或意见，请告之，感谢！！！

**Comment by lention** [comment]
补充下，我希望从broker获取offset，所以我用下面的方式获取broker的offset
offset = consumer.fetchConsumeOffset(queue, true);

下面代码获取store的时候总是为空
 var store = consumer.getOffsetStore();
                                    if (store!=null)
                                    {
                                        store.persist(queue);
                                    }  

以下为全部的代码
-----------------------------------------------------------------------------------------------------------

using java.util.concurrent;
using .Common;
using Thrift.Services;
using org.apache.rocketmq.client.consumer;
using org.apache.rocketmq.common.message;
using org.apache.rocketmq.common.protocol.heartbeat;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace RocketMq
{
    public static class RocketMqPullConsumer
    {
        private static string tag = "AnswerResult";
        private static string consumeGroup = "RawMessageConsumer_dev";
        private static string mqNameAddr = "192.168.0.0:9876";
        private static string topic = "AnswerRawMessage_dev";
        private static string instanceName = "0.47";
        private static bool isRunning = true;
        private static int batchSize = 5;
        public delegate bool OnMessageHandler(List<SaveAnswerResultRequest> msg);
        public static event OnMessageHandler OnMessageRecived;
        private static int SuccessInterval = 1000;
        private static int FailInterval = 2000;
        private static int EmptyInterval = 2000;

        public static void Stop()
        {
            isRunning = false;
        }
        public static void Start()
        {
            Task.Run(() =>
            {
                DefaultMQPullConsumer consumer = new DefaultMQPullConsumer(consumeGroup);
                consumer.setNamesrvAddr(mqNameAddr);
                consumer.setMessageModel(MessageModel.CLUSTERING);
                consumer.setInstanceName(instanceName);
                
                consumer.start();
                java.util.Set queues = null;
                MessageQueue queue = null;
                while (isRunning)
                {
                    try
                    {
                        queues = consumer.fetchSubscribeMessageQueues(topic);
                    }
                    catch (Exception)
                    {
                        // todo: 线程暂停，错误输出
                        Thread.Sleep(FailInterval);
                        continue;
                    }

                    if (queues == null)
                    {
                        Thread.Sleep(EmptyInterval);
                        continue;
                    }

                    if (queues.size() == 0)
                    {
                        Thread.Sleep(EmptyInterval);
                        continue;
                    }

                    CountDownLatch latch = new CountDownLatch(queues.size());
                    var queueList = queues.toArray();
                    foreach (var item in queueList)
                    {
                        queue = item as MessageQueue;
                        if (queue != null)
                        {
                            _ConsumeQueue(latch, consumer, queue);
                        }
                    }
                    try
                    {
                        latch.await();
                    }
                    catch (Exception)
                    {

                        throw;
                    }
                }
                consumer.shutdown();
            });

        }

        private static void _ConsumeQueue(CountDownLatch latch, DefaultMQPullConsumer consumer, MessageQueue queue)
        {
            Task.Run(() =>
            {
                bool isSuccess = false;
                long offset = 0;
                while (isRunning)
                {
                    try
                    {
                        offset = consumer.fetchConsumeOffset(queue, false);
                        if (offset < 0)
                        {
                            offset = 0;
                        }
                        List<SaveAnswerResultRequest> msgs = new List<SaveAnswerResultRequest>();
                        PullResult pullResult = consumer.pull(queue, null, offset, batchSize);
                        if (pullResult.getPullStatus() == PullStatus.FOUND)
                        {
                            var tempMsgs = pullResult.getMsgFoundList();
                            if (tempMsgs == null)
                            {
                                Thread.Sleep(EmptyInterval);
                                continue;
                            }
                            var temp = tempMsgs.toArray();
                            if (temp.Count() > 0)
                            {
                                foreach (var item in temp)
                                {
                                    var body = (item as MessageExt).getBody();
                                    if (body != null && body.Length > 0)
                                    {
                                        var obj = body.ConvertToObject<SaveAnswerResultRequest>();
                                        if (obj != null)
                                            msgs.Add(obj);
                                    }
                                }

                                if (OnMessageRecived != null)
                                {
                                    isSuccess = OnMessageRecived(msgs);
                                }
                                if (isSuccess)
                                {
                                    consumer.updateConsumeOffset(queue, pullResult.getNextBeginOffset());
                                    consumer.getDefaultMQPullConsumerImpl().updateConsumeOffsetToBroker(queue, pullResult.getNextBeginOffset(), false);
                                  
                                    consumer.getDefaultMQPullConsumerImpl().persistConsumerOffset();
                                    var store = consumer.getOffsetStore();
                                    if (store!=null)
                                    {
                                        store.persist(queue);
                                    }  
                                    Thread.Sleep(SuccessInterval);
                                }
                                else
                                {
                                    Thread.Sleep(FailInterval);
                                }
                            }
                            else
                            {
                                consumer.updateConsumeOffset(queue, pullResult.getNextBeginOffset());
                                var store = consumer.getOffsetStore();
                                if (store != null)
                                {
                                    store.persist(queue);
                                }
                                Thread.Sleep(EmptyInterval);
                            }

                        }
                        else
                        {
                            Thread.Sleep(EmptyInterval);
                        }

                    }
                    catch (Exception ex)
                    {
                        LogHelper.Error(ex.StackTrace);
                        Thread.Sleep(FailInterval);
                        //throw ex;
                    }
                }
                latch.countDown();
            });

        }
    }
}

**Comment by franknew** [comment]
这是转换后的bug。我的chainwaymq项目中有重写该方法。请去参阅。

**Comment by franknew** [comment]
public void UpdateOffset(MessageQueue queue, long offset)
        {
            var instance = this.getDefaultMQPullConsumerImpl().getmQClientFactory();
            ClientConfig clientConfig = this.cloneClientConfig();
            RemoteBrokerOffsetStore store = new RemoteBrokerOffsetStore(instance, this.getConsumerGroup());
            store.updateConsumeOffsetToBroker(queue, offset, true);
            this.setOffsetStore(store);
            this.updateConsumeOffset(queue, offset);
        }
