### ISSUE TITLE
steps  to   update dll  to  latest version

### ISSUE THREAD

**Issue by vikashsingh009** [franknew/RocketMQ-Client#3]
I  want  to  use  latest  version  of  Apache RocketMq 4.5.0 ,what  is  the  steps  to  create dll for  4.5.0  since  client-ikvm-4.2.0 its  working  fine  ,but  when  i  have  followed  below  steps

1) copy  all  jar  from  apche  rockermq  latest  lib  to  ikvm  lib

execute  ikvmc -out:rocketmq-all.dll ../lib/*.jar   that   generate  dll   ,put  refrence  for  dll,  but  producer always  complain  
No route info for this topic, testtopic
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/

**Comment by franknew** [comment]
this is not the latest rocketmq client, plz take a right version
